[package]
name = "file-scanner"
version = "0.1.0"
edition = "2021"
authors = ["File Scanner Project"]

[dependencies]
# Hash calculations
sha2 = "0.10"
md-5 = "0.10"
blake3 = "1.5"

# File metadata and system info
filetime = "0.2"
chrono = { version = "0.4", features = ["serde"] }

# Binary parsing
goblin = "0.8"  # For PE/ELF parsing
object = "0.36" # For object file parsing

# String extraction
regex = "1.10"
encoding_rs = "0.8"

# CLI and output
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async runtime (optional, for parallel processing)
tokio = { version = "1.40", features = ["full"] }

# Digital signature verification
ring = "0.17"

# MCP SDK
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main", features = ["transport-io"] }
schemars = "0.8"

# HTTP server for MCP
axum = { version = "0.7", features = ["ws"] }
tower = "0.5"
hyper = "1.5"
tokio-stream = "0.1"
futures-util = "0.3"
uuid = { version = "1.0", features = ["v4"] }

# Static analysis dependencies
addr2line = "0.21"
memmap2 = "0.9"
capstone = "0.11"
petgraph = "0.6"

# Threat detection
yara-x = "0.9"

[dev-dependencies]
tempfile = "3.8"