# cargo-release configuration
# https://github.com/crate-ci/cargo-release

[workspace]
# Ensure we're releasing from main branch
allow-branch = ["main", "master"]

# Sign commits and tags
sign-commit = true
sign-tag = true

# Update version in multiple files
pre-release-replacements = [
  {file="README.md", search="file-scanner = \"[^\"]*\"", replace="file-scanner = \"{{version}}\""},
  {file="src/main.rs", search="version = \"[^\"]*\"", replace="version = \"{{version}}\""},
  {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## [{{version}}] - {{date}}"},
  {file="CHANGELOG.md", search="\\[Unreleased\\]: https://github.com/vtriple/file-scanner/compare/v[^\\s]+\\.\\.\\.HEAD", replace="[Unreleased]: https://github.com/vtriple/file-scanner/compare/v{{version}}...HEAD\n[{{version}}]: https://github.com/vtriple/file-scanner/compare/v{{prev_version}}...v{{version}}"},
]

# Commit message for version bump
pre-release-commit-message = "chore: release {{version}}"

# Tag configuration
tag-message = "Release version {{version}}"
tag-name = "v{{version}}"

# Push to remote
push = true
push-remote = "origin"

# Publish to crates.io
publish = false  # Set to true when ready for crates.io

# Post-release version bump
post-release-commit-message = "chore: bump version to {{next_version}}"

# Changelog generation
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = """## [Unreleased]

## [{{version}}] - {{date}}"""
min = 0