blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/vtriple/file-scanner/security/advisories/new
    about: Please report security vulnerabilities privately
  - name: Questions & Discussions
    url: https://github.com/vtriple/file-scanner/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/vtriple/file-scanner/wiki
    about: Check the wiki for detailed documentation
